// Builds the JavaScriptCore bundle consumed by the Swift package.
//
//   npm run build
//
// Output:
//   ../Sources/PiDurableKit/Resources/pi-durable.js   the bundle (committed)
//   ../Sources/PiDurableKit/Resources/Documentation   pi-durable's README and type declarations (committed)
//   ../Sources/PiDurableKit/Resources/ThirdPartyNotices.txt  licenses of every package in the bundle (committed)
//   ../Sources/PiDurableKit/Generated/Versions.swift  the bundled package versions
//   src/versions.ts                                 the same versions for JavaScript
import { build } from "esbuild";
import { cpSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const output = resolve(root, "../Sources/PiDurableKit/Resources/pi-durable.js");
const versionsSwift = resolve(root, "../Sources/PiDurableKit/Generated/Versions.swift");

const version = (name) => JSON.parse(readFileSync(resolve(root, "node_modules", name, "package.json"), "utf8")).version;
const versions = {
	piDurable: version("@earendil-works/pi-durable"),
	piAI: version("@earendil-works/pi-ai"),
	chord: version("@earendil-works/chord"),
};

writeFileSync(
	resolve(root, "src/versions.ts"),
	`// Generated by build.mjs. Do not edit.\nexport const VERSIONS = ${JSON.stringify(versions, null, "\t")} as const;\n`,
);

mkdirSync(dirname(versionsSwift), { recursive: true });
writeFileSync(
	versionsSwift,
	`// Generated by JS/build.mjs. Do not edit.

extension PiDurable {
    /// The version of \`@earendil-works/pi-durable\` bundled into this package.
    public static let version = "${versions.piDurable}"
    /// The version of \`@earendil-works/pi-ai\` bundled into this package.
    public static let piAIVersion = "${versions.piAI}"
    /// The version of \`@earendil-works/chord\` bundled into this package.
    public static let chordVersion = "${versions.chord}"
}
`,
);

/**
 * Node built-ins reachable from the bundle, routed to host-backed shims. Each is limited to the importers that are
 * known to need it, so an unexpected new Node dependency fails the build instead of silently getting a shim.
 */
/**
 * pi-durable's documentation, as its npm package ships it: `README.md` and the `.d.ts` type declarations under `dist/`.
 * The bundle keeps only minified code, so this is how an app's agent can learn the API of the version it runs.
 */
function copyDocumentation() {
	const source = resolve(root, "node_modules/@earendil-works/pi-durable");
	const target = resolve(root, "../Sources/PiDurableKit/Resources/Documentation/pi-durable");
	rmSync(target, { recursive: true, force: true });
	mkdirSync(target, { recursive: true });
	cpSync(resolve(source, "README.md"), resolve(target, "README.md"));
	for (const entry of readdirSync(resolve(source, "dist"), { recursive: true }).sort()) {
		if (!String(entry).endsWith(".d.ts")) continue;
		const file = resolve(target, "dist", String(entry));
		mkdirSync(dirname(file), { recursive: true });
		const text = readFileSync(resolve(source, "dist", String(entry)), "utf8").replace(/\n?\/\/# sourceMappingURL=.*\n?$/, "\n");
		writeFileSync(file, text);
	}
}

copyDocumentation();

const shims = [
	{ module: "node:sqlite", file: "src/shims/node-sqlite.ts", importers: ["pi-durable/dist/storage/sqlite/node"] },
	{ module: "node:fs/promises", file: "src/shims/node-fs-promises.ts", importers: ["pi-durable/dist/storage/sqlite/node"] },
	{ module: "node:path", file: "src/shims/node-path.ts", importers: ["pi-durable/dist/storage/sqlite/node"] },
	{ module: "node:http", file: "src/shims/node-http.ts", importers: ["pi-ai/dist/auth/oauth/"] },
	{ module: "node:crypto", file: "src/shims/node-crypto.ts", importers: ["pi-ai/dist/auth/oauth/"] },
];

const nodeShims = {
	name: "pi-durable-kit-shims",
	setup(build) {
		build.onResolve({ filter: /^node:/ }, (args) => {
			const shim = shims.find(
				(candidate) => candidate.module === args.path && candidate.importers.some((importer) => args.importer.includes(importer)),
			);
			return shim === undefined ? undefined : { path: resolve(root, shim.file) };
		});
	},
};

const result = await build({
	entryPoints: [resolve(root, "src/bridge/index.ts")],
	outfile: output,
	bundle: true,
	format: "iife",
	platform: "browser",
	target: ["safari16"],
	// Minified for load time and app size; names are kept so errors (ConversationBusy, …) keep their names.
	minify: !process.argv.includes("--no-minify"),
	keepNames: true,
	legalComments: "none",
	charset: "utf8",
	plugins: [nodeShims],
	metafile: true,
	logLevel: "warning",
	banner: { js: `/* PiDurableKit bundle: pi-durable ${versions.piDurable}, pi-ai ${versions.piAI}, chord ${versions.chord} */` },
});

/**
 * The license notices of every npm package with code in the bundle, found from esbuild's metafile, so apps that ship
 * the bundle also ship the notices its licenses require (MIT, Apache-2.0, …), including Apache `NOTICE` files.
 */
/** License files of repositories whose npm packages omit them, vendored in `licenses/`. */
const repositoryLicenses = {
	// https://github.com/earendil-works/pi/blob/main/LICENSE: pi-durable, pi-ai, chord, pi-telemetry.
	"github.com/earendil-works/pi": "licenses/earendil-works-pi.txt",
	// https://github.com/standard-webhooks/standard-webhooks/blob/main/libraries/LICENSE: the JavaScript library (MIT).
	"github.com/standard-webhooks/standard-webhooks": "licenses/standard-webhooks.txt",
};

function writeNotices(metafile) {
	const packages = new Map();
	for (const input of Object.keys(metafile.inputs)) {
		const match = input.match(/^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//);
		if (match === null) continue;
		const directory = resolve(root, match[1]);
		const manifest = JSON.parse(readFileSync(resolve(directory, "package.json"), "utf8"));
		packages.set(`${manifest.name}@${manifest.version}`, { directory, manifest });
	}
	const textOf = (directory, pattern) =>
		readdirSync(directory)
			.filter((file) => pattern.test(file))
			.sort()
			.map((file) => readFileSync(resolve(directory, file), "utf8").trim());
	const sections = [...packages.entries()]
		.sort(([a], [b]) => a.localeCompare(b))
		.map(([id, { directory, manifest }]) => {
			const license = typeof manifest.license === "string" ? manifest.license : manifest.license?.type ?? "UNKNOWN";
			const texts = textOf(directory, /^(licen[cs]e|copying)(\.(md|txt))?$/i);
			// Packages published without their repository's license file (the pi monorepo's packages).
			const repository = String(manifest.repository?.url ?? manifest.repository ?? "");
			for (const [match, file] of Object.entries(repositoryLicenses)) {
				if (texts.length === 0 && repository.includes(match)) texts.push(readFileSync(resolve(root, file), "utf8").trim());
			}
			const notices = textOf(directory, /^notice(\.(md|txt))?$/i);
			if (texts.length === 0) throw new Error(`${id} ships no license file; add its notice by hand before bundling it`);
			const title = manifest.homepage ? `${id} (${license})\n${manifest.homepage}` : `${id} (${license})`;
			return [title, "", ...texts, ...notices].join("\n").trim();
		});
	const header = `PiDurableKit bundles the following open source packages in pi-durable.js.
Their licenses require these notices to accompany copies of the software.
Generated by JS/build.mjs from the bundled packages. Do not edit.`;
	const rule = `\n\n${"=".repeat(80)}\n\n`;
	writeFileSync(resolve(root, "../Sources/PiDurableKit/Resources/ThirdPartyNotices.txt"), `${header}${rule}${sections.join(rule)}\n`);
	console.log(`Wrote notices for ${packages.size} packages`);
}

writeNotices(result.metafile);

const bytes = Object.values(result.metafile.outputs)[0].bytes;
console.log(`Built ${output} (${(bytes / 1024 / 1024).toFixed(2)} MB) with pi-durable ${versions.piDurable}`);
